export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "forest-green": "#004225",
        "forest-green-alt": "#2C5530",
        primary: "#000000",
        "on-primary": "#ffffff",
        secondary: "#5d5f5f",
        "on-secondary": "#ffffff",
        background: "#f9f9f9",
        "on-background": "#1a1c1c",
        surface: "#f9f9f9",
        "on-surface": "#1a1c1c",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f3f3f4",
        "surface-container": "#eeeeee",
        "surface-container-high": "#e8e8e8",
        "surface-container-highest": "#e2e2e2",
        "surface-variant": "#e2e2e2",
        "on-surface-variant": "#4c4546",
        "primary-container": "#1b1b1b",
        "inverse-surface": "#2f3131",
        "inverse-on-surface": "#f0f1f1",
        outline: "#7e7576",
        "outline-variant": "#cfc4c5",
        error: "#ba1a1a",
        "on-error": "#ffffff",
      },
      fontFamily: {
        display: ["Chivo", "sans-serif"],
        headline: ["Chivo", "sans-serif"],
        body: ["Hanken Grotesk", "sans-serif"],
        label: ["Hanken Grotesk", "sans-serif"],
        "brand-display": ["Anton", "sans-serif"],
        "brand-body": ["Inter", "sans-serif"],
        "brand-label": ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "display-lg": ["72px", { lineHeight: "1.1", letterSpacing: "-0.04em", fontWeight: "800" }],
        "display-lg-mobile": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "800" }],
        "headline-lg": ["40px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg-mobile": ["32px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "700" }],
        "label-caps": ["12px", { lineHeight: "1.0", letterSpacing: "0.1em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
      },
      spacing: {
        "stack-xs": "0.25rem",
        "stack-sm": "0.5rem",
        "stack-md": "1rem",
        "stack-lg": "2rem",
        "stack-xl": "4rem",
        "stack-xxl": "8rem",
        "margin-desktop": "5rem",
        "margin-mobile": "1rem",
        gutter: "1.5rem",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
};
